[package]
name = "apa7"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Frank Lee"]
license = "MIT"
description = "APA 7th Edition student paper template for Typst"
homepage = "https://github.com/4anklee/apa"
repository = "https://github.com/4anklee/apa"
keywords = ["apa", "academic", "paper", "student", "citation", "essay"]
categories = ["paper"]
disciplines = ["psychology", "sociology", "education"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
